# Default values for spaceone.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

gracePeriod: 3 # for dev, long gracePeriod is useless

initializer:
  image: spaceone/spacectl:1.5.3
  imagePullPolicy: Always

mongo:
  enabled: true
  initialize: true
  image: mongo
  replicas: 1
  imagePullPolicy: IfNotPresent
  username: mongouser
  password: mongopassword
  host: mongo
  port: 27017
  service:
    type: ClusterIP
    annotations:
      nil: nil
    ports:
      - name: mongo
        port: 27017
        targetPort: 27017
        protocol: TCP

redis:
  enabled: true
  image: redis
  imagePullPolicy: IfNotPresent
  host: redis
  port: 6379
  service:
    type: ClusterIP
    annotations:
      nil: nil
    ports:
      - name: redis
        port: 6379
        targetPort: 6379
        protocol: TCP


consul:
  enabled: true
  image: consul:1.7.3
  imagePullPolicy: IfNotPresent
  host: consul
  service:
    type: ClusterIP
    annotations:
      nil: nil
    ports:
      - name: http
        port: 80
        targetPort: 8500
        protocol: TCP

      - name: httpd
        port: 8500
        targetPort: 8500
        protocol: TCP

backend:
  enabled: true
  replicas: 1
  revisionHistoryLimit: 3
  labels:
  imagePullPolicy: IfNotPresent

  services:
    config:
      enabled: true
      image: spaceone/config:1.5.3
      endpoint: config:50051
      service:
        type: ClusterIP
        annotations:
          nil: nil
        ports:
          - name: grpc
            port: 50051
            targetPort: 50051
            protocol: TCP

    identity:
      enabled: true
      image: spaceone/identity:1.5.3.1
      endpoint: identity:50051
      service:
        type: ClusterIP
        annotations:
          nil: nil
        ports:
          - name: grpc
            port: 50051
            targetPort: 50051
            protocol: TCP

    inventory:
      enabled: true
      image: spaceone/inventory:1.5.3.6
      endpoint: inventory:50051
      service:
        type: ClusterIP
        annotations:
          nil: nil
        ports:
          - name: grpc
            port: 50051
            targetPort: 50051
            protocol: TCP

    inventoryWorker:
      enabled: true
      image: spaceone/inventory:1.5.3.6
      replicas: 2
      service:
        type: ClusterIP
        annotations:
          nil: nil
        ports:
          - name: grpc
            port: 50051
            targetPort: 50051
            protocol: TCP

    inventoryScheduler:
      enabled: true
      image: spaceone/inventory:1.5.3.6
      service:
        type: ClusterIP
        annotations:
          nil: nil
        ports:
          - name: grpc
            port: 50051
            targetPort: 50051
            protocol: TCP

    monitoring:
      enabled: true
      image: spaceone/monitoring:1.5.3
      endpoint: monitoring:50051
      service:
        type: ClusterIP
        annotations:
          nil: nil
        ports:
          - name: grpc
            port: 50051
            targetPort: 50051
            protocol: TCP

    plugin:
      enabled: true
      image: spaceone/plugin:1.5.3
      endpoint: plugin:50051
      service:
        type: ClusterIP
        annotations:
          nil: nil
        ports:
          - name: grpc
            port: 50051
            targetPort: 50051
            protocol: TCP

    repository:
      enabled: true
      image: spaceone/repository:1.5.3.1
      endpoint: repository:50051
      service:
        type: ClusterIP
        annotations:
          nil: nil
        ports:
          - name: grpc
            port: 50051
            targetPort: 50051
            protocol: TCP
      ECR:
        enabled: false
        host: https://<your ECR url>>

    secret:
      enabled: true
      image: spaceone/secret:1.5.3
      endpoint: secret:50051
      service:
        type: ClusterIP
        annotations:
          nil: nil
        ports:
          - name: grpc
            port: 50051
            targetPort: 50051
            protocol: TCP

      awsSecretManagerConnector:
        awsAccessKeyId: 
        awsSecretAccessKey: 
        regionName: ap-northeast-2

    statistics:
      enabled: true
      image: spaceone/statistics:1.5.3
      endpoint: statistics:50051
      service:
        type: ClusterIP
        annotations:
          nil: nil
        ports:
          - name: grpc
            port: 50051
            targetPort: 50051
            protocol: TCP

    statisticsScheduler:
      enabled: true
      image: spaceone/statistics:1.5.3
      service:
        type: ClusterIP
        annotations:
          nil: nil
        ports:
          - name: grpc
            port: 50051
            targetPort: 50051
            protocol: TCP

    billing:
      enabled: true
      image: spaceone/billing:1.5.3
      service:
        type: ClusterIP
        annotations:
          nil: nil
        ports:
          - name: grpc
            port: 50051
            targetPort: 50051
            protocol: TCP

    power_scheduler:
      enabled: false
      image: spaceone/power_scheduler:1.5.3
      endpoint: power_scheduler:50051
      service:
        type: ClusterIP
        annotations:
          nil: nil
        ports:
          - name: grpc
            port: 50051
            targetPort: 50051
            protocol: TCP

    cost_saving:
      enabled: false
      image: spaceone/cost_saving:1.5.3
      endpoint: cost_saving:50051
      service:
        type: ClusterIP
        annotations:
          nil: nil
        ports:
          - name: grpc
            port: 50051
            targetPort: 50051
            protocol: TCP


frontend:
#  domain: root # 안먹힘
  enabled: true
  replicas: 1
  imagePullPolicy: IfNotPresent

  console:
    enabled: true
    image: spaceone/console
    tag: 1.5.3
    host: console
    service:
      type: ClusterIP
      annotations:
        nil: nil
      extraSpec:
        nil: nil
      ports:
        - name: http
          port: 80
          targetPort: 80
          protocol: TCP
        - name: https
          port: 443
          targetPort: 80
          protocol: TCP

    domainName:
      ref: config # hostname
      name: root # megazone

  consoleApi:
    enabled: true
    endpoint: console-api
    protocol: http # https
    image: spaceone/console-api:1.5.3.1
    service:
      type: ClusterIP
      annotations:
        nil: nil
      extraSpec:
        nil: nil
      ports:
        - name: http
          port: 80
          targetPort: 80
          protocol: TCP
        - name: https
          port: 443
          targetPort: 80
          protocol: TCP


supervisor:
  enabled: true
  imagePullPolicy: Always
  supervisor:
    image: spaceone/supervisor:1.5.3
    replicas: 1
    imagePullPolicy: Always
    token: # yaml for TOKEN or TOKEN_INFO
      protocol: consul
      config:
        host: "{{ .Values.consul.host }}"
      uri: debug/supervisor/TOKEN
    plugin:
      imageRepository: pyengine
      replicas: "{{ .Values.backend.services.inventoryWorker.replicas }}"

  kubectlProxy:
    image: spaceone/kubectl-proxy

ingress:
  enabled: false
  annotations:
    nil: nil
  tls:
    enabled: true
#######
# Vault reference : https://www.vaultproject.io/docs/platform/k8s/helm/configuration
#######
#vault:
#  global:
#    enabled: true
#  server:
#    dev:
#      enabled: true
#  name: hello
