{{- if .Values.backend.enabled }}
  {{- if .Values.backend.services.billing.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-conf
  namespace: {{ .Release.Namespace }}
data:
  billing.yml: |
    GLOBAL:
      DATABASES:
        default:
          db: 'dev-billing'
          host: {{ .Values.mongo.host }}
          port: {{ .Values.mongo.port }}
          maxPoolSize: 200
          username: {{ .Values.mongo.username }}
          password: {{ .Values.mongo.password }}
      CACHES:
        default:
          backend: spaceone.core.cache.redis_cache.RedisCache
          host: {{ .Values.redis.host }}
          port: {{ .Values.redis.port }}
          db: 5
          encoding: utf-8
          socket_timeout: 10
          socket_connect_timeout: 10
      LOG:
        loggers:
          spaceone:
            handlers:
              - console
              - file
        handlers:
          file:
            type: file
            filename: /logs/billing.log
      CONNECTORS:
        IdentityConnector:
          endpoint:
            v1: grpc://{{ .Values.backend.services.identity.endpoint }}
        InventoryConnector:
          endpoint:
            v1: grpc://{{ .Values.backend.services.inventory.endpoint }}
        PluginConnector:
          endpoint:
            v1: grpc://{{ .Values.backend.services.plugin.endpoint }}
        RepositoryConnector:
          endpoint:
            v1: grpc://{{ .Values.backend.services.repository.endpoint }}
        SecretConnector:
          endpoint:
            v1: grpc://{{ .Values.backend.services.secret.endpoint }}
      HANDLERS:
        authentication:
          - backend: spaceone.core.handler.authentication_handler.AuthenticationGRPCHandler
            uri: grpc://{{ .Values.backend.services.identity.endpoint }}/v1/Domain/get_public_key
            #        authorization:
            #          - backend: spaceone.core.handler.authorization_handler.AuthorizationGRPCHandler
            #            uri: grpc://{{ .Values.backend.services.identity.endpoint }}/v1/Authorization/verify
  {{- end }}
{{- end }}
